### ISSUE TITLE
Codify cert generation. 

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#1]
Generating the certs can (and should?) be scripted. Submitting the readily made certs creates a blind spot to the workflow. How about if you script the cert generation and commit the scripts instead of the actual certs?

**Comment by evilon** [comment]
ping @jviide @aleksiklasila - is this issue obsolete already?

**Comment by jviide** [comment]
I defer to @aleksiklasila's judgement.

**Comment by Mamietti** [comment]
Codified into the trytls backend and trytls runner
