### ISSUE TITLE
stubs have redundant license and author info

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#100]
Now stub `README.md` files have extra maintenance overhead from redundant link to license and author info that has to be manually updated instead of just relying on the version history or possible notes in the code files themselves. At some point in future someone might regret this source of extra work. :)

**Comment by Mamietti** [comment]
I might get the licence but why adding original author is not good?

**Comment by Mamietti** [comment]
@ikisusi also some of the stubs have pretty much lost their history. I say we leave the original author.

**Comment by ikisusi** [comment]
I random sampled one stub and it said **Author**, not _Original author_. This means that you have a place to update when someone else has authored, modified, fixed the stub. Have you actually captured all the authors successfully? This makes me think that it would be less work to rely on the version control system's blame. List the contributors (for now in the main README.md) and maybe later on in the release notes to pull latest ones better to spotlight. Problem now is that e.g. you might have modified a stub that says that the author is someone else, and wrong person gets the blame/fame. I think many of us have fiddled with many of the stubs with fixes and if we have done stupid things, wrong person would now get the blame. Authors also agreed to being listed in the contributors list, but not necessary agreed to be blamed for the whole stub when someone else might have fiddled with it. Authors furthermore have had the opportunity to write their names in the source files or README-files already, and many have chosen not to do so.

**Comment by aleksiklasila** [comment]
closed by a2f0808 30fab03 e930a9e 04fa290 commits.
