### ISSUE TITLE
tox.ini limits tests to runners/trytls only

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#101]
For some reason current tox.ini limits pytest and flake8 run to runners/trytls only. Is this desirable?

**Comment by Mamietti** [comment]
ping @aleksiklasila & @jviide I'd like to hear the reasoning for this as well

**Comment by jviide** [comment]
`py.test` tries to evaluate the Python files it encounters. For the current Python stubs this means the same thing as running the stubs. This in turn causes errors like this:

``` sh
____________ ERROR collecting stubs/python-urllib2/run.py ____________
stubs/python-urllib2/run.py:6: in <module>
    exit("Usage: %s <HOST> <PORT> [CA_FILE]" % sys.argv[0])
.tox/py27/lib/python2.7/site.py:403: in __call__
    raise SystemExit(code)
E   SystemExit: Usage: .tox/py27/bin/py.test <HOST> <PORT> [CA_FILE]
```

Directories could be selectively ignored, if so desired.

`flake8` appears to be Python version specific, so running it with Python 3.x will yield syntax errors for Python 2 code (that is not valid Python 3 code) and vice versa. For example running the Python 3 version of `flake8` for the whole repository outputs, among other things, the following error:

``` sh
./stubs/python-idiokit/run.py:26:19: E999 SyntaxError: invalid syntax
```

The error code flake8 versions < 3 was E901, but the same idea applies.

**Comment by Mamietti** [comment]
Sounds reasonable.
