### ISSUE TITLE
move to mandatory pull request model with master

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#121]
At some point we should consider stabilising the master  by moving to pull request model and blocking direct commits to master. Would this make sense and if so, what would be sensible milestone to do it?

**Comment by Mamietti** [comment]
Yes. This.

**Comment by Mamietti** [comment]
The single file fixes would become a bit intensive. Not a large nuisance but a thing to consider. However, if the github native editor is excluded from the block then this point is invalid.

**Comment by Mamietti** [comment]
Moved.
