### ISSUE TITLE
Wrong version gets installed when using pip install

### ISSUE THREAD

**Issue by mikkoyli** [ouspg/trytls#131]
I tried to install trytls by following this documentation: https://github.com/ouspg/trytls/blob/master/README.md

I installed pip using following command:
pip install trytls

When I try to run python-urllib2 stub I get the following output. When installed with pip the old version gets installed.

`
mikko@mikko-Latitude-E6330:~/git/trytls/stubs/python-urllib2$ trytls https python run.py
platform: Linux (neon 16.04)
runner: trytls 0.1.1 (CPython 2.7.12, OpenSSL 1.0.2g-fips)
stub: python 'run.py'
ERROR expired certificate [reject expired.badssl.com:443]
      reason: unexpected output                                                                                                                                                            
      output: REJECT 
...
`

When installed trytls from repo, the trytls seems to be the newest version even though the version number appears to be the old one.

**Comment by Mamietti** [comment]
@mikessu See if the new release v0.2.0 fixed it

**Comment by mikkoyli** [comment]
Works now!
