### ISSUE TITLE
Proposal: Rename python-* stubs to python2-*

### ISSUE THREAD

**Issue by jviide** [ouspg/trytls#192]
Python2 stub directories are prefixed with `python-`, while Python3 stub dirs are prefixed with `python3-`.  Due to the ambiguity several people have tried to run `python-` stubs with Python3 (warning: anecdotal data 😉).

Maybe we should prefix Python2 stubs with `python2-`?

**Comment by ikisusi** [comment]
This would help e.g. in shootout result presentation. :)
