### ISSUE TITLE
badssl.com has introduced some new tests

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#194]
badssl.com has introduced some new tests. It might be good idea to go through the current set of tests and integrate anything worthy into TryTLS.

**Comment by aleksiklasila** [comment]
# Badssl tests

to me it appears as...

## Currently
- [x] sni
- [x] self-signed
- [x] expired
- [x] wrong.host
- [x] sha256
- [x] 1000-sans
- [x] incomplete-chain
- [x] superfish
- [x] edellroot
- [x] dsdtestprovider
- [x] superfish
- [x] eDellRoot

## some of these might still be worth consideration
- [x] untrusted-root
- [x] rc4-md5
- [x] rc4
- [x] null
- [ ] 10000-sans
- [x] some of the dh ones
