### ISSUE TITLE
Language specific campaigns

### ISSUE THREAD

**Issue by Mamietti** [ouspg/trytls#22]
- [ ] ruby
- [x] php
- [ ] rust
- [ ] golang
- [x] [idiokit](https://github.com/abusesa/idiokit)
- [ ] css
- [ ] ...

**Comment by oherrala** [comment]
Here's list of what languages are most common in github repositories: http://githut.info/

However, going per language might not be enough. There's high probability of more than one TLS library per language.

**Comment by evilon** [comment]
Checking the projects currently pondering TLS-issues might be a good start.

**Comment by oherrala** [comment]
Good amount of programming language stubs have been made and [shootouts](https://github.com/ouspg/trytls/tree/master/shootout#readme) to collect results. Closing.
