### ISSUE TITLE
Only one java stub needed in the shootouts?

### ISSUE THREAD

**Issue by aleksiklasila** [ouspg/trytls#247]
java-https and java-net seem to be closely related and should work the same (https). It's probably useless to test the both in shootouts. Maybe we should do the shootouts without the java-net stub - and possibly consider removing the java-net results from the previous shootouts (if seen useful and easy enough to actually perform).

**Comment by Mamietti** [comment]
@aleksiklasila If you can find evidence that they use the same code

**Comment by Mamietti** [comment]
Let's see in the next shootout. (Whenever there is one)
