### ISSUE TITLE
MVP result collection

### ISSUE THREAD

**Issue by Mamietti** [ouspg/trytls#27]
Plan some sort of result backend service (domain integration, within stub directories, runner integration - where?)

**Comment by Mamietti** [comment]
Well, the runners can be made to print results from the command line itself (add that to docs?) so it is then domain and/or stub directory choice.

**Comment by Mamietti** [comment]
My plan is: Have the results of a test run for a stub be inside its directory and the domain should at least either reference this fact or even better, provide them as a separate service. As in, one can go to trytls.io to see how a library+language combo did in a multi-backend test.

**Comment by Mamietti** [comment]
For MVP we will now collect results of the test run of a stub in its own directory. Do this for **all** stubs just before release. Of course, practicing beforehand is not forbidden. I say we add it to a file called results.md for clarity.

**Comment by evilon** [comment]
@Mamietti Did you decide that the results are not part of MVP?

**Comment by Mamietti** [comment]
@evilon We are currently deciding. We are thinking about what audience we would lose if we did not include results.

**Comment by Mamietti** [comment]
Fixed by 33fc0c1
