### ISSUE TITLE
Find new tests

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#283]
Create new issue from https://github.com/ouspg/trytls/issues/140#issuecomment-238207154:

Checking from [here](https://www.stackage.org/haddock/lts-6.6/x509-validation-1.6.3/Data-X509-Validation.html#g:2), we could try to find tests for the following
- validity starts after checking time
- not a CA/unknown Certificate Authority (CA)
- connection name and certificate do not match
- invalid wildcard in certificate

**Comment by wbond** [comment]
Currently the following are covered by the badtls.io tests:
- validity starts after checking time (future.badtls.io:11001)
- connection name and certificate do not match (domain-mismatch.badtls.io:11002)

When you say "invalid wildcard in certificate", it isn't clear to me if you mean the certificate contains an invalidly-encoded wildcard, of if you are looking for a wildcard mismatch. If you want a mismatch, that is handled by wildcard.mismatch.badtls.io:11007.

You could test "unknown Certificate Authority (CA)" by trying domain-match.badtls.io:10000 without the custom CA cert.

Generally I'm happy to add tests to badtls.io to test out various constructs. The python scripts that are part of https://github.com/wbond/badtls.io make it fairly easy to construct various good and bad configurations.

**Comment by jviide** [comment]
Spoke with @oherrala in real life&trade; about this. @wbond is correct in all cases.
- **validity starts after checking time** is handled by `future.badtls.io:11001`.
- **not a CA/unknown Certificate Authority (CA)** is currently handled by `self-signed.badssl.com:443`.
- **connection name and certificate do not match** is tested by `domain-mismatch.badtls.io:11002`.
- **invalid wildcard in certificate** is covered by `wildcard.mismatch.badtls.io:11007`, which tests the wildcard `*.badtls.io` against `wildcard.mismatch.badtls.io`. As always, there could be more tests, like `foo.*.example.com`, `f*.example.com` or `*.*.example.com`.

All in all, it looks like it's ok to close this issue.
