### ISSUE TITLE
cve{,2}.freakattack.com gone?

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#293]
Lets see if this is just temporary issue or will it persist. If this is permanent, we need to remove tests.

``` console
$ host cve.freakattack.com
Host cve.freakattack.com not found: 3(NXDOMAIN)

$ host cve2.freakattack.com
Host cve2.freakattack.com not found: 3(NXDOMAIN)
```

**Comment by jviide** [comment]
Yeah, they seem to be still offline. Let's remove those tests.
