### ISSUE TITLE
Replace StartCom-issued certs with certs from a different CA

### ISSUE THREAD

**Issue by briansmith** [ouspg/trytls#296]
I don't think an implementation should have to trust StartCom's roots in order to pass the test, but I'm told that is currently the case today.

**Comment by jviide** [comment]
Newly-released [TryTLS v0.3.7](https://github.com/ouspg/trytls/releases/tag/v0.3.7) contains pull request #300 that removed tlsfun.de tests.

**Comment by briansmith** [comment]
Thanks!
