### ISSUE TITLE
backends/trytls/configs/create_servers - take care of priv key permissions? 

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#34]
@aleksiklasila, [backends/trytls/configs/create_servers](https://github.com/ouspg/trytls/blob/10f0cd714f49b3a13a6b9b5d3203f8cfaa20d12e/backends/trytls/configs/create_servers) seems to take care that the certificate is world readable. Should it take care that private key is not?

**Comment by Mamietti** [comment]
Fixed by 35703a5
