### ISSUE TITLE
showrunner & stubs - could show errors more clearly

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#38]
Right now, if the stub fails, there are situations where it is hard to understand where the error is coming from. More info will follow, right now just creating a drive-by ticket.

**Comment by evilon** [comment]
Bit-by-bit, now an example dump. 

The scenario is a first time user who has vague understanding of the concepts in trytls (runner, bundles, stubs). He/She runs one stub and gets for example the output below. (This is a bad example as the issue is at urllib3 -stub, but lets continue from here.)

It is a bit hard to decide from where to start the issue hunt. 

Maybe trytls could tell that it tried to execute a command X. And _maybe_ imply that the unexpected output came from the stub. 

``` sh
$ trytls -t .https.all_tests python run.py               
ERROR unexpected output:

ERROR unexpected output:

ERROR unexpected output:

ERROR unexpected output:

ERROR unexpected output:
....
```

**Comment by evilon** [comment]
trytls now returns what the unexpected input was, like this:

``` sh
 ERROR unexpected output:
    VERIFY SUCCESSX
```

This is helpful, thanks!

Now, could tryls also tell on failure, how it tried to run the stub? When the docs have been read and understood, it of course is pretty obvious. But might be helpful for first-time user to see how the stub was run during the failure:

Now, here we have a case where the stub incorrectly implements the calling convention, and 
the stub ends up exiting in confusion: 

```
ERROR process exited with return code 1
```

How about something among these lines:

```
ERROR process exited with return code 1 when executing the test:
python python-urllib2/run.py sha256.badssl.com 443 
```

^- point over there is not the formatting. Just the concept of telling how the stub was run.

**Comment by evilon** [comment]
Just to +1, we just had a case where user wrote "echo" stub to observe the arguments the trytls is giving to the stub.

**Comment by jviide** [comment]
`python python-urllib2/run.py sha256.badssl.com 443` would probably be ok but on the other hand the localhost tests would look something like `python python-urllib2/run.py localhost 64633 /some/very/noisy/path/to/cabundle.pem` where both e.g. `/some/very/noisy/path/to/cabundle.pem` wouldn't exist after the test has finished.

**Comment by jviide** [comment]
@evilon regarding your 

> trytls now returns what the unexpected input was, like this:
> 
> ``` sh
>  ERROR unexpected output:
>     VERIFY SUCCESSX
> ```

This behavior is not new. In fact in the previous example

``` sh
ERROR unexpected output:

ERROR unexpected output:

```

the output _is_ printed, but the output is empty or just whitespaces. Of course this can be made more explicit (for example printing "empty output" or something), but just wanted to point out that this particular behavior hasn't changed.

**Comment by jviide** [comment]
Has merging PR #82 fixed this issue? The current output looks like this:

```
 PASS expired certificate [reject expired.badssl.com:443]
ERROR wrong hostname in certificate [reject wrong.host.badssl.com:443]
      reason: no output
 PASS self-signed certificate [reject self-signed.badssl.com:443]
ERROR SHA-256 signature [accept sha256.badssl.com:443]
      reason: unexpected output
      output: VERIFY SUCCESSX
```

**Comment by evilon** [comment]
Output looks good to me. Thanks!

**Comment by jviide** [comment]
Great! Closing this issue.
