### ISSUE TITLE
Documentation for each stub and reinforce protocol conformity

### ISSUE THREAD

**Issue by Mamietti** [ouspg/trytls#39]
No new stubs accepted without them, and no changes to old ones until them. They are now very hard to run by a common user. Also, we have to ensure all stubs follow the protocol defined in stubs/README.md.

**Comment by Mamietti** [comment]
ping @joneskoo on the go stub

**Comment by oherrala** [comment]
@Mamietti, can you give us example or documentation how to document stubs?

**Comment by Mamietti** [comment]
HaskellNet and java-https stubs have a good example. It shows if there is any dependencies, building or other things you must do to run the example. Add the (host) (port) (ca-bundle) format just in case if one disregards the general readme.

**Comment by joneskoo** [comment]
@Mamietti I'd suggest also documenting how the stubs should be implemented, e.g. CA certificate bundle as PEM provided in environment variable `SSL_CERT_FILE`; exit code 1 for TLS verification failed, 1 for success, and standard output for a descriptive message. That way it's simple to set them up to a common runner.

The stubs are anyway built for this project so there's no reason why they shouldn't be built in common format.

**Comment by joneskoo** [comment]
- [x] bash-curl
- [ ] dotnet-https
- [x] go-nethttp
- [x] haskell-HaskellNet
- [x] haskell-wreq
- [x] java-https
- [x] lua5.1-luasec
- [x] python-urllib3
- [ ] python3-imaplib
- [ ] python3-urllib

modified by @Mamietti to update luastub location

**Comment by joneskoo** [comment]
@jviide pointed out privately that README has the common format already defined. Maybe this belongs to README under stubs/ and not main README. https://github.com/ouspg/trytls#calling-convention

**Comment by jviide** [comment]
It might be a good idea to move the stub "protocol" documentation from the main `README.md` file to `stub/README.md`. Please note that the protocol has changed somewhat (`VERIFY SUCCESS`, `VERIFY FAILURE` and `UNSUPPORTED`). The protocol is indeed there to establish an easy way to run tests with a runner, and there are already two runners in the works (Python and bash).

The Python `trytls` runner can be installed with `pip install .` or with the usual `python setup.py install` command (`--user` setting is recommended in both cases). Currently the running instructions are somewhat scattered over the main `README.md` and the `showrunner/README.md` files.

**Comment by oherrala** [comment]
@joneskoo

> exit code 1 for TLS verification failed, 1 for success, and standard output for a descriptive message.

It's better to explicitly state the verification result instead of magic exit codes. If the stub worked like it should, exit code should be 0 and the verdict of test is signalled by printing "VERIFY FAILURE", "VERIFY SUCCESS" or "UNSUPPORTED".

Doing it that way leaves any other return value (commonly considered as errors in UNIX) for real error signalling (like uncaught exception which killed the program). Stating the verdict by printing it to stdout and exiting with 0 is kind of proof that the test succeed. Any other exit is implementation error in stub.

**Comment by joneskoo** [comment]
Ossi, either way. There are many examples of tests that return status in exit code. Like most unit test utilities I know return 1 if any tests failed. Also your standard /bin/false etc. Many tools use other codes to
indicate specific other errors, for example wget https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html

I see the interface has already been selected so better stick with the one you chose. In any case a strict interface specification and an interface validation test helps. I'll wait for things to stabilize.

I won't make more changes now but anyone is free to update the stub to match current trytls interface.

**Comment by ikisusi** [comment]
Problem with using exit code for test verdict in this case is that the stub actually doesn't know what is the test purpose and can't act as the test oracle itself. Ie. in some cases VERIFY SUCCESS is test verdict pass or fail. That why we currently think that the stub should return 0 and "VERIFY SUCCESS" or "VERIFY FAILURE" if it was able to conduct the test and return 1 and possible error trace/information if it was not. Then actual test oracle with the verdict generation is in the runner which actually know if the verify should have succeeded for the given test, and the runner then returns exit value accordingly to be used in the unit testing. Ie. I see your point about unit tests returning the exit value, but in this case it feels like that the oracle is in the runner and the stub is not a test in itself.

**Comment by jviide** [comment]
@joneskoo After a recent change (see #36) the `trytls` tool exits with exit code 3 if there is a test failure or some kind of error. The _stubs_ are really meant to be run using these tools (called _runners_), not by themselves. It's the runner's job to prepare the test input and collect the results. For example, using the tool to run the Go stub (slightly modified to match the protocol) looks something like this:

``` sh
$ trytls go run stubs/go-nethttp/run.go 
PASS badssl(False, 'expired')
PASS badssl(False, 'wrong.host')
PASS badssl(False, 'self-signed')
PASS badssl(True, 'sha256')
...
```

**Comment by Mamietti** [comment]
Progress update on protocols and READMEs:
Otherwise looks great but python3-urllib is missing documentation. Adding go stub argument example...soon.

**Comment by Mamietti** [comment]
Tested all stubs running them using their respective documentation. Made a few changes and hence I am closing this.
