### ISSUE TITLE
TryTLS runner install problem on Ubuntu 16.04 container

### ISSUE THREAD

**Issue by Mamietti** [ouspg/trytls#47]
Running pip `install .` in command line gives:

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Here is what `local` prints out:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by Mamietti** [comment]
108 from AskUbuntu question [here](http://askubuntu.com/questions/17001/how-to-set-locale) helped.

Thing to notice is that you have to do the `pip install .` as root (not with user via ssh connection) or else it does not accept the install. This good?

**Comment by ikisusi** [comment]
@Mamietti Running as root comment is misplaced here? Not related to orginal issue? Deserves its own issue or disucssion?

**Comment by jviide** [comment]
Also, it might be a good idea to document the actual solution here.

**Comment by Mamietti** [comment]
So the trick is to install the language locales with:
`sudo apt-get install language-pack-en-base`

Then reconfigure locals:
`sudo dpkg-reconfigure locales`

"en_US.utf8" for both prompts and it should do the trick.

**Comment by ikisusi** [comment]
Related? https://github.com/pypa/pip/issues/3575 ... so actual solution might be just to run non-buggy version of pip. However setting up locales properly is a good ideas as well.
