### ISSUE TITLE
Add Contributors section to README.md?

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#49]

**Comment by jviide** [comment]
What should this section in README.md contain? A list of contributors, instructions for potential contributors - or something else?

**Comment by ikisusi** [comment]
Pointer to CONTRIBUTING.md and list of contributors so far to give people some very visible fame for their volunteer work. Ie. not just have the team there. Gives also an excuse to sync with early stage contributors to ask if they want to appear there and how.
