### ISSUE TITLE
Community update

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#51]
# Minimum viable product 1.0

We were lucky to get contributors early on on the project. TryTLS has been in flux, but now things start to stabilise and an idea of the roadmap exists. Hence, it is now time to update the contributors on the progress for better synchronisation.  
## Overview

![mvp](https://raw.githubusercontent.com/ouspg/trytls/master/doc/mvp.jpg)

The minimum viable product will contain the following:

Python-based `trytls` runner

Stubs for the following languages:
- Lua
- Python
- Go
- Haskell
- Java

Support for two backends
- [BadSSL](https://badssl.com)
- [SSL Labs](https://www.ssllabs.com)

Documentation:
- _For end users_: Step-by-step guide on how to run a stub with or without a runner, with some information on backends
- _For developers_: Information on how to create a stub using correct calling convention (more on it below)
## Stub progress

We have agreed on an initial common [calling convention](https://github.com/ouspg/trytls/tree/master/stubs).
## License

We have added a default [license](https://github.com/ouspg/trytls/blob/master/LICENSE). Please drop us a note in the comment field, wether default license is ok for you.
## Contributors list

Every contributor will get a mention in the main `README.md`. It is also possible to negotiate a different arrangement if it suits your preference.
## What's next?

We will add more stubs, runners and backends in the future versions.
# Checklist
- [x] Check if default license is ok for contributors
- [x] Check how contributors want to be named on the contributor list

**Comment by evilon** [comment]
Default license is ok for me.

**Comment by Mamietti** [comment]
Ok for me as well.

**Comment by Mamietti** [comment]
Ping: @aleksiklasila @jviide @ikisusi @oherrala @ppietikainen @joneskoo

**Comment by oherrala** [comment]
I'm ok with default license (MIT).

**Comment by jviide** [comment]
MIT license ok for me.

**Comment by ikisusi** [comment]
Ok with MIT. If needed CC0 or similar with other material (pictures, videos) produced by me is ok as well if we need to go beyond MIT.

**Comment by ppietikainen** [comment]
Ok with MIT

**Comment by joneskoo** [comment]
My contributions are OK to distribute under MIT license.
