### ISSUE TITLE
Runners should check for SNI support early on in the test?

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#75]
Running e.g. against badssl without first checking if the stub supports SNI leads to many false verdicts. Maybe runners could first check the preconditions and then skip tests that are invalid if preconditions for those tests are not satisfied (e.g. no-SNI support vs. badssl).

**Comment by oherrala** [comment]
This is related to #87.

**Comment by Mamietti** [comment]
#108 closed this

Edited: Almost closed this 😄

**Comment by ppietikainen** [comment]
Another thing that could be worth sanity-checking is whether the stub can open a valid CA file, (e.g. trytls https docker exec <stub> cannot, despite the stub supporting custom CA bundles)

**Comment by oherrala** [comment]
> Another thing that could be worth sanity-checking is whether the stub can open a valid CA file, (e.g. trytls https docker exec cannot, despite the stub supporting custom CA bundles)

@ppietikainen, this more relevant to issue #87.

**Comment by oherrala** [comment]
Fix candidate for this can be found in #190.
