### ISSUE TITLE
Clarify passing arguments beginning with a hyphen to stubs

### ISSUE THREAD

**Issue by jviide** [ouspg/trytls#83]
Currently there is a problem in situations when `trytls` needs to pass arguments starting with a hyphen (`-`) to the stub. One such example is running a stub with Docker:

``` sh
$ trytls https docker run --rm foobar
usage: trytls BUNDLE -- COMMAND [ARG ...]
trytls: error: unrecognized arguments: --rm foobar
```

The `trytls` tool assumes that the `--rm` parameter is a non-positional argument. The way to avoid this is the classic double-hyphen:

``` sh
$ trytls https -- docker run --rm foobar
```

However there is still room for confusion, as using `--` is not enforced and the error messages when one forgets to use it are less than helpful. Possible solutions:
1. Enforce `--` as a separator between the tool arguments and the stub command. This would at least be explicit.
2. Modify `trytls` so that everything after the first COMMAND argument is passed to the stub as-is. I'd guess this is the way most first-time users would assume how the tool to works.
3. Take the stub command as one argument, e.g.:
   
   ``` sh
   $ trytls https 'docker run --rm foobar'
   ```

Thoughts or suggestions?

**Comment by jviide** [comment]
Ping @oherrala who has had to wrestle with this.

**Comment by Mamietti** [comment]
Option **3.** would be the clearest for me (okay, it takes this command thing and runs it) but **2.** might indeed be good for first timers. I think **1.** would be too easy to miss.

**Comment by Mamietti** [comment]
We'll use the double hyphen. Easy, clear.

**Comment by Mamietti** [comment]
Actually...option 2. would be better.
