### ISSUE TITLE
Machine-readable output for trytls

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#96]
For centralised result collecition, machine-readable output would be nice. 
This is not a top priority for the moment, just creating the ticket for consideration for future enhancement. 

For the format, I propose line separated JSON, with all the version info included (and the result of course) in each line. It would make the result collection pretty straight forward. It could happen **for example** like this:

``` sh
cat stubs/*/results.json | python resultcollector.py > results.csv
```

**Comment by jviide** [comment]
Some other options are:
- Just a JSON object that contains all the information (results, platform info, ...) in one object. 
- The JUnit format several CI systems appear to support (Jenkins, CircleCI, ...)
