### ISSUE TITLE
Acceptance process for current stubs

### ISSUE THREAD

**Issue by aleksiklasila** [ouspg/trytls#97]
Here is the checklist of the 0.2.0 stubs to take through the [acceptance process](../blob/master/stubs/README.md#acceptance-process).
- [x] bash-curl
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] bash-opensslSClient
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] c-openssl
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] cSharp-Net
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] dotnet-https
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] FSharp-Net
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] go-nethttp
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] haskell-wreq
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] java-https
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] java-net
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] lua5.1-luasec
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] php-file-get-contents
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] python3-urllib
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] python-idiokit
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] python-requests
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] python-urllib2
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] python-urllib3
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings
- [x] vb-net
  - [x] License + author
  - [x] Contribution list
  - [x] Specs
  - [x] Stub works
  - [x] Docs + dependencies
  - [x] Results
  - [x] Findings

**Comment by Mamietti** [comment]
Consider it done.
